### ISSUE TITLE
Train issues

### ISSUE THREAD

**Issue by rwywenyi** [LIAGM/DAEFR#2]
when i try train sh scripts/run_LQ_codebook_training.sh.
error happen:
Traceback (most recent call last):
  File /aigc-nas01/renwenyi/DAEFR/main_for_codebook.py:570
    data.prepare_data()
  File ~/anaconda3/envs/gfpgan/lib/python3.10/site-packages/pytorch_lightning/core/datamodule.py:92 in wrapped_fn
    return fn(*args, **kwargs)
  File ~/anaconda3/envs/gfpgan/lib/python3.10/site-packages/pytorch_lightning/utilities/distributed.py:35 in wrapped_fn
    return fn(*args, **kwargs)
  File /aigc-nas01/renwenyi/DAEFR/main_for_codebook.py:188 in prepare_data
    instantiate_from_config(data_cfg)
  File /aigc-nas01/renwenyi/DAEFR/main_for_codebook.py:152 in instantiate_from_config
    return get_obj_from_str(config["target"])(config.get("params", dict()))
  File /aigc-nas01/renwenyi/DAEFR/main_for_codebook.py:23 in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File ~/anaconda3/envs/gfpgan/lib/python3.10/importlib/__init__.py:126 in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File <frozen importlib._bootstrap>:1050 in _gcd_import
  File <frozen importlib._bootstrap>:1027 in _find_and_load
  File <frozen importlib._bootstrap>:992 in _find_and_load_unlocked
  File <frozen importlib._bootstrap>:241 in _call_with_frames_removed
  File <frozen importlib._bootstrap>:1050 in _gcd_import
  File <frozen importlib._bootstrap>:1027 in _find_and_load
  File <frozen importlib._bootstrap>:1004 in _find_and_load_unlocked
ModuleNotFoundError: No module named 'DAEFR.data'

where is the DAEFR.data?

**Comment by LIAGM** [comment]
Hi,

Thanks for pointing out this issue!

I have checked that it is due to the setting of my .gitignore file.
I have modified the settings and updated the repo.
Please pull the updated files.

Please let me know if you have other questions.
