### ISSUE TITLE
ValueError: The provided lr scheduler "[<torch.optim.lr_scheduler.MultiStepLR object at 0x7f91a1f05cd0>, <torch.optim.lr_scheduler.MultiStepLR object at 0x7f91a1f05d30>]" is invalid

### ISSUE THREAD

**Issue by ThediidehT** [LIAGM/DAEFR#4]
pytorch_lightning 1.0.8 do not support multistep scheduler

**Comment by sunzhe09** [comment]
+1

**Comment by LIAGM** [comment]
Hi,

Could you please provide more detailed information about this issue?
I never encounter this error during my whole project with the same environment.

**Comment by sunzhe09** [comment]
it the environment problem thx

**Comment by order-a-lemonade** [comment]
> Hi,
> 
> Could you please provide more detailed information about this issue? I never encounter this error during my whole project with the same environment.

encounter environment problem too. i am  also using a100 gpu. could you please share your pytorch version? 1.13.1 is not ok on my device.

**Comment by LIAGM** [comment]
Hi,

I have provided the [environment.yml](https://github.com/LIAGM/DAEFR/blob/master/environment.yml) for installation.
The pytorch version is 1.10.1
Have you tried that?

**Comment by order-a-lemonade** [comment]
> Hi,
> 
> I have provided the [environment.yml](https://github.com/LIAGM/DAEFR/blob/master/environment.yml) for installation. The pytorch version is 1.10.1 Have you tried that?

sry, didn't notice it before. i will try it.  
btw, how does the batchsize influence the results of stage3? thank u very much.

**Comment by LIAGM** [comment]
Hi,

We have tried different batch sizes before, and the influence is very little.
Just to make sure the total epoch is the same.

BTW, when do you encounter this issue, during training or testing?
Thanks.

**Comment by LIAGM** [comment]
Hi all,

I have updated the environment setting and tested this setting can work well for training and testing.
Please follow the [Environment](https://github.com/LIAGM/DAEFR?tab=readme-ov-file#environment) part to set up.
Thanks.
